name: isolate_pool_2
description: Jut like a thread pool, but with isolates
version: 1.0.0
homepage: https://github.com/maxim-saplin/isolate_pool

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  test:
  lints: 
