name: isolate_pool_2
description: Just like a thread pool, but with isolates. The package allows creating up-and-running set of isolates that accept requests (aka pooled jobs) or host Dart instances that can accept incoming (from main isolate) requests via Action objects
version: 1.0.1
homepage: https://github.com/maxim-saplin/isolate_pool

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  test:
  lints: 
